TextEditor/urls.py
from django.conf.urls import include, url
import django.contrib.auth.views
from django.contrib import admin
from . import views
from webapps import settings
from django.views.static import serve
from TextEditor.forms import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.loadDashboard),
    #url(r'^$', views.signup),#django.contrib.auth.views.login, {'template_name':'login.html'}),
    url(r'^login$', django.contrib.auth.views.login, 
        {'template_name':'signup.html', 
        'extra_context': {'signupform': SignupNewUser()}},
        name='login'),
	url(r'^signup$', views.signup, name = 'signup'),
    url(r'^profile$', views.profile, name='profile'),
    url(r'^update_profile$', views.updateProfile, name='profile'),
    url(r'^save_document/(?P<docID>\d+)', views.saveDocument, name='save_document'),
    url(r'^dashboard', views.loadDashboard, name = 'dashboard'),
    url(r'^editor/(?P<docID>\d+)', views.loadEditor),
    url(r'^share/(?P<docID>\d+)', views.share, name='share'),
    url(r'^load_document/(?P<docID>\d+)', views.loadDocument),
    url(r'^confirm/(?P<token>\S+)', views.confirm_registration, name = 'confirm'),
    url(r'^translate/(.+?)/(\S+)', views.translate),
    url(r'^lookup/(.*)', views.lookup),
    url(r'^logout$', django.contrib.auth.views.logout_then_login, name='logout'),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^delete_document/(?P<docID>\d+)', views.deleteDocument, name='delete_document'),
    url(r'^email-for-password-reset$',views.email_for_password_reset, name='email_for_password_reset'),
    url(r'^reset-password/(?P<token>\S+)$', views.reset_password, name = 'reset_password'),

]

webapps/urls.py
from django.conf.urls import include, url
import django.contrib.auth.views
from django.contrib import admin
import TextEditor.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', django.contrib.auth.views.login, {'template_name':'login.html'}, name='login'),
]

TextEditor/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django.dispatch import receiver
import os

# Create your models here.
class MUser(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	activation_key = models.CharField(max_length=40)
	password_key = models.CharField(max_length=40)
	def natural_key(self): 
		return (self.user.first_name, self.user.id)	

class Document(models.Model):
	title = models.CharField(max_length=100)
	author = models.ForeignKey(MUser, on_delete=models.CASCADE)
	date_created = models.DateTimeField()
	date_modified = models.DateTimeField()

class CachedItem(models.Model):
	key = models.CharField(max_length=100)
	data_type = models.CharField(max_length=50)
	data_file = models.FileField()

@receiver(models.signals.post_delete, sender=CachedItem)
def auto_delete_file_on_delete(sender, instance, **kwargs):
	# source: http://stackoverflow.com/questions/16041232/django-delete-filefield
    if instance.data_file:
        if os.path.isfile(instance.data_file.path):
            os.remove(instance.data_file.path)

TextEditor/forms.py
from django import forms

from django.contrib.auth.models import User
from TextEditor.models import *

class UpdateUserInfoForm(forms.Form):
	first_name = forms.CharField(max_length=200, label='First Name', required=False)
	last_name = forms.CharField(max_length=200, label='Last Name', required=False)
	email = forms.EmailField(label='Email Address', required=False)
	password1 = forms.CharField(max_length=200, 
								widget = forms.PasswordInput(),
								label="Password", required=False)
	password2 = forms.CharField(max_length=200, 
								widget = forms.PasswordInput(),
								label="Confirm Password", required=False)
	def clean(self):
		# Calls our parent (forms.Form) .clean function, gets a dictionary
		# of cleaned data as a result
		cleaned_data = super(UpdateUserInfoForm, self).clean()
		# Confirms that the two password fields match

class SignupNewUser(forms.Form):
	first_name = forms.CharField(max_length=40, widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'First Name'}))
	last_name = forms.CharField(max_length=40, widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Last Name'}))
	username = forms.CharField(max_length = 20, widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Username'}))
	user_email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Email'}))
	password1 = forms.CharField(max_length = 200,label='Password',widget = forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'Password'}))
	password2 = forms.CharField(max_length = 200,label='Confirm password', widget = forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'Confirm Password'}))
	def clean(self):
		cleaned_data = super(SignupNewUser, self).clean()
		password1 = cleaned_data.get('password1')
		password2 = cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords did not match.")
		# Generally return the cleaned data we got from our parent.
		return cleaned_data

	def clean_username(self):

		username = self.cleaned_data.get('username')
		if User.objects.filter(username=username):
			raise forms.ValidationError("Username is already taken.")
		return username
	def clean_user_email(self):

		user_email = self.cleaned_data.get('user_email')
		if User.objects.filter(email=user_email):
			raise forms.ValidationError("Email is already taken.")
		return user_email
class EmailForm(forms.Form):
	user_email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Email'}))
	def clean(self):
		cleaned_data = super(EmailForm, self).clean()
		return cleaned_data	
class PasswordResetForm(forms.Form):
	password1 = forms.CharField(max_length = 200,label='Password',widget = forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'Password'}))
	password2 = forms.CharField(max_length = 200,label='Confirm password', widget = forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'Confirm Password'}))
	def clean(self):
		cleaned_data = super(PasswordResetForm, self).clean()
		password1 = cleaned_data.get('password1')
		password2 = cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords did not match.")
		# Generally return the cleaned data we got from our parent.
		return cleaned_data

class shareForm(forms.Form):
	user_email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Email'}))
	def clean(self):
		cleaned_data = super(shareForm, self).clean()
		return cleaned_data

TextEditor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db import transaction
from django.http import HttpResponse, Http404
# Decorator to use built-in authentication system
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models  import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.tokens import default_token_generator
from mimetypes import guess_type
# Imports the Comment class
from TextEditor.models import *
from TextEditor.forms import *
#EMAIL
from django.core.mail import send_mail
import datetime
import django.contrib.staticfiles
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.shortcuts import render_to_response
from django.db.models import Q
from django.core.files import File
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.core import serializers
import hashlib
import requests
import context
import json
import googleTest
import urllib
import boto3
import os
citationDiv = '*=======================Citations=======================*'
from django.contrib.auth.views import login as core_login

#myapp/views.py
# @ratelimit_post(minutes = 1, requests = 4, key_field = 'username')

# def login(request,template_name):
#     from django.contrib.auth import authenticate
#     user = authenticate(request.username, request.password)
#     #template_name = "template_name" + "aaaaa"
#     return core_login(request, template_name)
@login_required
def deleteDocument(request,docID):
	print("DOCUMENT TO DELETE")
	print(docID)
	errors = []
	context = {}

    # Deletes the item if present in the todo-list database.
	try:
		item_to_delete = Document.objects.get(id=docID)
		item_to_delete.delete()
	except ObjectDoesNotExist:
		raise Http404("Document does not exist")

	muser = MUser.objects.get(user_id=request.user.id)
	documents = Document.objects.filter(author_id=muser.id)
	context['documents'] = documents
	context['first_name'] = request.user.first_name
	context['errors'] = errors
	# #print documents[0].title
	# context['first_name'] = request.user.first_name
	return redirect('/dashboard')

@login_required
def loadEditor(request, docID):
	#print( int(docID) == 0)
	if int(docID) == 0:
		doc = Document(title="Untitled Document",
			date_created=datetime.datetime.now(),
			date_modified=datetime.datetime.now(),
			author=MUser.objects.get(user_id=request.user.id))
		doc.save()
		print doc.id
		return redirect('/editor/'+str(doc.id))
	else:
		try:
			doc = Document.objects.get(id=docID, author=MUser.objects.get(user_id=request.user.id))
		except:
			raise Http404("Document does not exist")
		context = {'docID': docID,
					'title': doc.title}

	return render(request, 'editor.html', context)

@login_required
def share(request, docID):
	form = shareForm(request.POST)
	if form.is_valid():
		email = form.cleaned_data['user_email']
		users = User.objects.filter(email=email)
		if len(users) == 0:
			return HttpResponse(json.dumps(json.dumps({'status': 0}), content_type='application/json'))
		else:
			user = users[0]
			try:
				doc = Document.objects.get(id=docID, author=MUser.objects.get(user_id=request.user.id))
			except:
				raise Http404("Wrong Request")
			newDoc = Document(title=doc.title,
								date_created=doc.date_created,
								date_modified=doc.date_modified,
								author=MUser.objects.get(user_id=user.id))
			newDoc.save()
			s3 = boto3.resource('s3')
			s3.meta.client.download_file('smartexdocuments', str(docID)+'.txt', 'TextEditor/Documents/'+request.user.username+'.temp')
			with open('TextEditor/Documents/'+request.user.username+'.temp', 'r') as fin:
				content = fin.read()
				with open('TextEditor/Documents/'+request.user.username+'.temp','w') as fout:
					mFile = File(fout)
					mFile.write(content)
				s3 = boto3.client('s3')
				s3.upload_file('TextEditor/Documents/'+request.user.username+'.temp', 'smartexdocuments', str(newDoc.id)+'.txt')

			return HttpResponse(json.dumps({'status': 1}), content_type='application/json')

@login_required
def saveDocument(request,docID):
	if request.method != "POST":
		return render(request, 'editor.html', {})
	# #print request.POST['title']
	# path = default_storage.save('/path/to/file', ContentFile('new content'))
	try:
		muser = MUser.objects.get(user_id=request.user.id)
		doc = Document.objects.get(id=docID, author_id=muser.id)
	except:
		raise Http404("Wrong Request")
	# if len(docs) > 0:
	# 	doc = docs[0]
	with open('TextEditor/Documents/'+request.user.username+'.temp','w') as f:
		mFile = File(f)
		mFile.write(request.POST['content'])
		mFile.write(citationDiv)
		mFile.write(request.POST['citations'])
	s3 = boto3.client('s3')
	s3.upload_file('TextEditor/Documents/'+request.user.username+'.temp', 'smartexdocuments', str(docID)+'.txt')
	doc.date_modified=datetime.datetime.now()
	doc.title = request.POST['title']
	doc.save()
	os.remove('TextEditor/Documents/'+request.user.username+'.temp')
	context = {'docID': docID,
					'title': doc.title}
	# else:
	# 	with open('TextEditor/Documents/'+muser.user.username+'.temp','w') as f:
	# 		mFile = File(f)
	# 		mFile.write(request.POST['content'])
	# 		mFile.write(citationDiv)
	# 		mFile.write(request.POST['citations'])
	# 	s3 = boto3.client('s3')
	# 	s3.upload_file('TextEditor/Documents/'+muser.user.username+'.temp', 'smartexdocuments', muser.user.username+title+'.txt')
	# 	doc = Document(title=title,
	# 		date_created=datetime.datetime.now(),
	# 		date_modified=datetime.datetime.now(),
	# 		author=MUser.objects.get(user_id=request.user.id))
	# 	doc.save()
	# 	os.remove('TextEditor/Documents/'+muser.user.username+'.temp')
	return render(request, 'editor.html', context)

@login_required
def loadDashboard(request):
	print('________________LOAD DASHBOARD CALLED___________________________')
	context = {}
	muser = MUser.objects.get(user_id=request.user.id)
	documents = Document.objects.filter(author_id=muser.id)
	context['documents'] = documents
	context['first_name'] = request.user.first_name
	# #print documents[0].title
	# context['first_name'] = request.user.first_name
	return render(request, 'dashboard.html', context)

def loadDocument(request, docID):
	doc = Document.objects.get(id=docID)
	s3 = boto3.resource('s3')
	s3.meta.client.download_file('smartexdocuments', str(docID)+'.txt', 'TextEditor/Documents/'+request.user.username+'.temp')
	with open('TextEditor/Documents/'+request.user.username+'.temp', 'r') as f:
		[content,citations] = f.read().split(citationDiv)[:2]
	resp = {'content': content,
			'citations': citations}
	os.remove('TextEditor/Documents/'+request.user.username+'.temp')
	print (docID, content, citations)
	return HttpResponse(json.dumps(resp), content_type='application/json')	

@login_required
def getProfilePicture(request, uid):
	try:
		muser = MUser.objects.get(user_id=uid)
	except:
		raise Http404("User Does Not Exist")
	if not muser.profile.picture:
		content_type = guess_type(settings.MEDIA_ROOT+'John_Doe.jpg')
		print (os.getcwd())
		f = open(settings.MEDIA_ROOT+'profile_pictures/John_Doe.jpg')
		return HttpResponse(File(f), content_type=content_type)
	content_type = guess_type(muser.profile.picture.path)
	return HttpResponse(muser.profile.picture, content_type=content_type)

@login_required
def profile(request):
	muser = MUser.objects.get(user_id=request.user.id)
	print (muser.activation_key)

	user = muser.user
	context = {}
	# context['picture'] = '/grumblr/DP/'+uid

	context['full_name'] = user.first_name+' '+user.last_name
	context['username'] = user.username
	context['email'] = user.email
	return render(request, 'profile.html', context)	

@login_required
def updateProfile(request):
	muser = MUser.objects.get(user_id=request.user.id)
	form = UpdateUserInfoForm(request.POST)
	context={}
	context['form'] = form
	if request.method == 'GET':
		return render(request,'update_profile.html', context)
	if not (form.is_valid()):
		return render(request,'update_profile.html', context)
	for field in form.fields:
		if 'password' in field:
			continue
		if form.cleaned_data[field]:
			setattr(request.user, field, form.cleaned_data[field])
			request.user.save()
	if 'password1' in form.fields:
		print('updated password')
		request.user.set_password(form.cleaned_data['password1'])
		request.user.save()
	return redirect('/profile')
@transaction.atomic
def signup (request):
    print('______________WENT THOUGH SIGNUP______________')
    context = {}
    if request.method == 'GET':
        context['signupform'] = SignupNewUser()
        return render(request, 'signup.html',context)

    signupform = SignupNewUser(request.POST)
    context['signupform'] = signupform
    if not signupform.is_valid():
        return render(request, 'signup.html', context)

    new_user = User.objects.create_user(first_name = signupform.cleaned_data['first_name'],\
                                        last_name = signupform.cleaned_data['last_name'],\
                                        username = signupform.cleaned_data['username'], \
                                        email = signupform.cleaned_data['user_email'],\
                                        password=signupform.cleaned_data['password1'])
    #new_user = authenticate(username=request.POST['username'], \
    #                        password=request.POST['password1'])
    new_user.is_active = 0

    new_user.save()
    #new_user_profile = UserProfile( user = new_user,\
    #                                first_name = form.cleaned_data['first_name'],\
    #                                last_name = form.cleaned_data['last_name'])
    #new_user_profile.save()
    newUser = MUser(user=new_user)
    print(signupform.cleaned_data['username'])
    username = signupform.cleaned_data['username']
    h = hashlib.sha224(username.encode('utf-8'))
    token = h.hexdigest()[:40]

TextEditor/templates/base.html
<!DOCTYPE HTML>
<html>
<head>
{% include 'bootstrap_stuff.html' %}
{% include 'javascript.html' %}
{% include 'head_css.html' %}
{% block local_css %}
{% endblock local_css %}
{% block local_js %}
<!-- this block contains the js files that are only specific to certain page-->
{% endblock local_js %}
</head>
<body>
{% block background_img %}
{% endblock background_img %}
<nav class="navbar navbar-default" style="background-color: #499CCA;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="pull-left" href="#"><img class="logo" src="../static/images/gicon.png" alt="hello"></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
    {% block navbarButtons %}
    {% endblock navbarButtons %}
    </ul>
    {% block login %}
    {% endblock login %}
     </div>
  </div>
</nav>

{% block body %}
{% block main_container %}
{% endblock main_container %}

{% endblock body %}



</body>
</html>

TextEditor/templates/dashboard.html
{% extends 'base.html' %}
{% block local_css %}
	<link rel="stylesheet" href="/static/css/dashboard.css">
{% endblock local_css%}
{% block navbarButtons %}
<!--     <li class="active"><a class="nav_btn" href="dashboard">Dashboard <span></span></a></li>
    <li><a href="profile" class="nav_btn">My profile <span ></span></a></li> -->
	<li ><span class= 'nav_btn_holder' = ><a class="nav_btn" href="{% url 'dashboard' %}"> Dashboard </a></span></li>
    <li ><span class= 'nav_btn_holder' = ><a class="nav_btn" href="profile"> My profile </a></span></li>
    {% endblock navbarButtons %}
    {% block login %}
    <a  href='/logout' type="submit" role = "button" class="logout-btn">Logout</a>
    {% endblock login %}
{% block body %}
	<div class='row'>
		<div class='col-md-1'></div>
		<div class='col-md-10'>
			<h1> Welcome {{ first_name }} </h1>
			<a href='editor/0' role='button' type="button" class="btn mButton">Start New Document</a> <br>
			{% for doc in documents %}
				
					<div class='doc_thumb col-md-2'>
						<a href="{% url 'delete_document' doc.id %}"><span class="glyphicon glyphicon-remove pull-right deleteDocument" aria-hidden="true"></span></a>
						<div class='row'>
							<div class='doc_name col-md-2'>
				
								<a href="editor/{{ doc.id }}">
									<p class='lead'>{{ doc.title }}</p>
								</a>
							</div>						
						</div>
						<div class='row'>
							<div class='col-md-1'>
								<span class="glyphicon glyphicon-time"></span>
							</div>
							<div class='col-md-10'>
								<p>{{ doc.date_modified }}</p>
							</div>
						</div>
					</div>
			{% endfor %}
		</div>
		<div class='col-md-1'></div>
	</div>

	
{% endblock %}

TextEditor/templates/editor.html
{% extends 'base.html' %}

{% block local_css %}
<!-- Theme included stylesheets -->
<link href="https://cdn.quilljs.com/1.1.3/quill.snow.css" rel="stylesheet">
<link href="https://cdn.quilljs.com/1.1.3/quill.bubble.css" rel="stylesheet">
<link rel="stylesheet" href="/static/css/editor.css">
{% endblock %}
{% block local_js %}
<!-- Main Quill library -->
<script src="https://cdn.quilljs.com/1.1.3/quill.js" type="text/javascript"></script>
<script src="https://cdn.quilljs.com/1.1.3/quill.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.debug.js"></script>
<script src='/static/js/queue_implementation.js'></script>
<script src='/static/js/reconnecting-websocket.min.js'></script>
<script src='/static/js/editor.js'></script>


<script src='/static/js/translate.js'></script>
<script type='text/javascript'>
	loadDocument({{ docID }})
</script>
{% endblock %}
{% block navbarButtons %}
    <li ><span class= 'nav_btn_holder' = ><a class="nav_btn" href="{% url 'dashboard' %}"> Dashboard </a></span></li>
    <li ><span class= 'nav_btn_holder' = ><a class="nav_btn" href="/profile"> My profile </a></span></li>
    <!-- <li ><a href="/profile" class="nav_btn">My profile <span ></span></a></li> -->
{% endblock navbarButtons %}


{% block login %}
    <a  href='/logout' type="submit" role = "button" class="logout-btn">Logout</a>
{% endblock login %}


{% block body %}
	<div class='row'>
		<div class='col-md-1'></div>
		<div class='col-md-7'>
			<div id='document_data'>
				<span>
					<input type='text' value='{{ title }}' placeholder='Enter Document Title' class='doc_title'></input>
					<button type="button" class ='btn btn-primary' id = "share_btn"> share </button>
					
				</span>
				<span style="display:none; width:100px;" id = "share_success" class="alert alert-success">
					    <strong>shared!</strong>
					  </span>
			</div>
		</div>
		<div class='col-md-4'>
			<p id='saveTime'></p>
		</div>
		<div class='col-md-1'>
			<div id="divdeps" style="display:none" title="">


				<form id="dialog_form" class="navbar-form navbar-right" method="post" action="{% url 'share' docID %}" accept-charset="UTF-8">
		        <div class="input-group">
		            <input class="form-control" id="id_user_email" name="user_email" placeholder="Email" type="text">
		        </div>
		        <span>
		        <input type="submit" id = "dialog_share" class="my-button"></input>
		        <input type="hidden" />
		                {% csrf_token %}
		        </span>
				
			</div>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-1'></div>
		<div class='col-md-2 pane'>
			<div class='row' style='background-color:#EEEEEE;'>
				<h3 align='center'>References</h3>
			</div>
			<div id="citationPane"></div>
			
		</div>
		<div class='col-md-5'>
			<div id='editor-container'>
				<div id='editor'></div>
				{% csrf_token %}
			</div>
		</div>
		<div class='col-md-3 pane' id="suggestionsPane">
			<div class='row' style='background-color:#EEEEEE;'>
				<h3 align='center'>Suggestions</h3>

			</div>
			<div id='general_info'> 
				<h4 class = "info_title"> General Info </h4> 
				<ul style="list-style: none"; id = "general_info_list"> </ul>
			</div>
			<br>
			<div id='text_replacement'> 
				<h4 class = "info_title">Text Replacement </h4>
				<ul style="list-style: none"; id = "text_replacement_list"> </ul>
			</div>
			<br>
			<div id='related_links'> 
				<h4 class = "info_title">Related Links </h4>
				<ul style="list-style: none"; id = "related_links_list"> </ul>
			</div>
		</div>
		<div class='col-md-1'></div>
	</div>
{% endblock %}

TextEditor/templates/email_for_password_reset.html
{% extends 'base.html' %}

{% block body_background %}
<body background="../static/images/white.jpg">
{% endblock body_background %}

{% block navbar_buttons %}
		<li class="active"><a href="">Home <span class="sr-only">(current)</span></a></li>
{% endblock navbar_buttons %}



{% block main_container %}
    <p> {{message}}
    <form action="{% url 'email_for_password_reset' %}" method="post">
    <table>
    {{email_form}}
    </table>
    <input type="submit" value="submit">
    {% csrf_token %}
    </form>

    
{% endblock main_container %}

TextEditor/templates/javascript.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="/static/js/jquery-2.1.4.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>

TextEditor/templates/login.html
{% extends 'base.html' %}
{% block background_img %}
<img src="../static/images/bg9.jpg" alt="hello" class="blur-bg" />
{% endblock background_img %}
{% block login %}
{% include 'loginnavbar.html' %}
{% endblock login %}
{% block body %}

    <h1> HELLO from login </h1>
{% endblock body %}

TextEditor/templates/loginnavbar.html
{% block login %}
        
      <form id="signin" class="navbar-form navbar-right" method="post" role="form" action="{% url 'login' %}" accept-charset="UTF-8">
        <div class="input-group">
        
        <a style = "color:white" href="{% url 'email_for_password_reset' %}" class="forgot_pwd">forgot password?</a>
        {% if form.errors %}
            <a id="wrong_credentials" class="pull-right" style="color:red">
              Incorrect user name or password.
            </a>
        {% endif %}
        </div>
        <div class="input-group">
            <input id="username" type="username" class=" username form-control" name="username" value="" placeholder="username" required>
        </div>

        <div class="input-group">
            <input id="password" type="password" class="password form-control" name="password" value="" placeholder="Password" required>
        </div>
        <span>
        <button type="submit" class="my-button">Login</button>
        <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
        </span>
     </form>
        

{% endblock login %}

TextEditor/templates/navbar.html
<nav class="navbar navbar-default" style="background-color: #499CCA;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="pull-left" href="/"><img class="logo" src="../static/images/gicon.png" alt="hello"></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
    {% block navbarButtons %}
    <li class="active"><a class="nav-btn" href="">Dashboard <span></span></a></li>
    <li><a href="" class="nav-btn">My profile <span ></span></a></li>
    {% endblock navbarButtons %}
    </ul>
    <a  href='/logout' type="submit" role = "button" class="logout-btn">Logout</a>
     </div>
  </div>
</nav>

TextEditor/templates/needs-confirmation.html
{% extends 'base.html' %}
{% block background_img %}
{% endblock background_img %}
{% block navbar %}
{% include 'loginnavbar.html' %}
{% endblock navbar %}
{% block main_container %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
        	<div class = "email-ver">
            	<h1> please go to {{email}} to verify your email address </h1>
            </div>
        </div>
    </div>
</div>
{% endblock main_container %}